services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Lemming\Imageoptimizer\:
    resource: '../Classes/*'

  Lemming\Imageoptimizer\Report\StatusReport:
    autoconfigure: true

  Lemming\Imageoptimizer\EventListener\BeforeFileAdded:
    tags:
      - name: event.listener
        identifier: 'ImageOptimizer'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileAddedEvent
  Lemming\Imageoptimizer\EventListener\BeforeFileReplaced:
    tags:
      - name: event.listener
        identifier: 'ImageOptimizer'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileReplacedEvent
  Lemming\Imageoptimizer\EventListener\AfterFileProcessing:
    tags:
      - name: event.listener
        identifier: 'ImageOptimizer'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileProcessingEvent
